### ISSUE TITLE
subreddit_stats crashed when displaying a large report

### ISSUE THREAD

**Issue by amici-ursi** [praw-dev/prawtools#23]
The resulting message is too big. Not submitting.
    Subreddit Stats: destinythegame top posts from 2014-06-17 to 2015-01-28 08:49 PD
    T
    Traceback (most recent call last):
      File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Python34\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Python34\Scripts\subreddit_stats.exe\__main__.py", line 9, in <module
    >
      File "C:\Python34\lib\site-packages\prawtools\stats.py", line 576, in main
        options.commenters, 5, 5, options.top, options.debug)
      File "C:\Python34\lib\site-packages\prawtools\stats.py", line 465, in publish_
    results
        print(body)
      File "C:\Python34\lib\encodings\cp437.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_map)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position
    1919: character maps to <undefined>
    sys:1: ResourceWarning: unclosed <socket.socket fd=376, family=AddressFamily.AF_
    INET, type=SocketType.SOCK_STREAM, proto=0, laddr=('192.168.0.4', 63783), raddr=
    ('xxx.xx.xxx.xxx', xxx)>
    C:\Python34\lib\importlib\_bootstrap.py:2150: ImportWarning: sys.meta_path is em
    pty
    sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=548, family=AddressFamily.AF_
    INET, type=SocketType.SOCK_STREAM, proto=0, laddr=('192.168.0.4', 62277), raddr=
    ('xxx.xx.xxx.xxx', xxx)>

**Comment by wtchen** [comment]
How big is the desired report in question?

**Comment by psdtwk** [comment]
I was hoping pretty big, but that info is all it gave me.

**Comment by wtchen** [comment]
What's the command string?...

**Comment by psdtwk** [comment]
subreddit_stats -t all -u USERNAME -p PASSWORD -R subreddit_stats -vvv -c 30 -s 30

**Comment by CeruleanSky** [comment]
For people having this issue, go into Lib\site-packages\prawtools\stats.py and change
MAX_BODY_SIZE = 10000 to the new maximum
MAX_BODY_SIZE = 40000

If your post still can't be submitted, its length is beyond what reddit itself supports and you'll have to look into other ways of getting your report, like reducing the submitter/commiter values, making it a csv, etc.

**Comment by bboe** [comment]
This issue should be resolved with the increase to 40,000 and the adaptive decrease in number of submissions to show.
