### ISSUE TITLE
Update to OAuth?

### ISSUE THREAD

**Issue by amici-ursi** [praw-dev/prawtools#26]
I receive this message when running `subreddit_stats`:

> DepreiationWarning: Password-based authentication will stop working on 2015-08-03 and as a result will be removed from Praw4.

Are there plans to update PRAWtools to OAuth?

**Comment by bboe** [comment]
Updating PRAW to OAuth only is the priority. Unfortunately I have little use for this utility these days and little time to maintain projects that I'm not actively using. Hopefully someone who uses it can step up and modify it to work via OAuth.

**Comment by psdtwk** [comment]
It seems like I'm the primary user.

I'm currently working my way through CSS, then JavaScript. I'll go back to Python afterwards and see if I can get it working.

Thanks

**Comment by bboe** [comment]
I updated the master branch to use PRAW4 thus resulting in the need for OAuth. I've tested that some of the flows work and added travis and coveralls to the project to assist with code coverage. There may be some bugs so I do not intend to make an official release until the code coverage is up for all the tools.
