### ISSUE TITLE
Reduce Memory Consumption

### ISSUE THREAD

**Issue by bboe** [praw-dev/prawtools#39]
Stats bot, which continuously runs subreddit_stats, was consuming over 4.6GB of memory. That's too much. Rather than saving all the submissions and comments for later aggregation, they should be processed and discarded immediately.

**Comment by bboe** [comment]
This doesn't appear to be as big of an issue, but it is still problematic. After running for a few days it's consuming over 350MB.

**Comment by teaearlgraycold** [comment]
Why not utilize sqlite? It would also allow for SQL to be written for the analytics.

**Comment by bboe** [comment]
I have no desire to persist the results for the purposes of this tool.

**Comment by bboe** [comment]
This appears to now be resolved:

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                    
12599 ec2-user  20   0  244m  51m 5432 S  0.0  5.2  84:12.11 statsbot
```
