### ISSUE TITLE
Flair commands not updated to work with praw4

### ISSUE THREAD

**Issue by Aeon** [praw-dev/prawtools#40]
Trying to get list of flairs for a subreddit, getting the following error:

```
AttributeError: 'Subreddit' object has no attribute 'get_flair_list'
```

Is the tool actually updated to use praw4 completely, or is it unsafe to use? I don't want to destroy my subs' current properties :)

**Comment by bboe** [comment]
This tool has not yet been updated to use praw4. You'll want to use v0.19 to use the flair commands. We can keep this issue open, as I do intend to update it. I believe PRAW4 supports all the necessary features, I just haven't had a reason until now to actually update this last file of the project.

Do you have any interest in helping?

**Comment by Aeon** [comment]
I could help a bit, but I don't really know python well. 

Looking at the praw4 source, I don't see any methods to manage flair templates in [`SubredditFlair` class](https://github.com/praw-dev/praw/blob/praw4/praw/models/reddit/subreddit.py#L189). Am I missing something, or were they just removed entirely?

**Comment by Aeon** [comment]
I tried switching to older version

```bash
pip install 'praw<=2.1.17' 'prawtools<=0.19.3'    
# ....                                                                                                      
Installing collected packages: praw, prawtools
Successfully installed praw-2.1.17 prawtools-0.19.3
```

 but can't get it to work either:

```bash
modutils --flair-stats wingchun -vvv                                                                                                                      

Version 0.19.3 of prawtools is outdated. Version 0.21.1 was released 6 days ago.
Traceback (most recent call last):
  File "/usr/local/bin/modutils", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/prawtools/mod.py", line 280, in main
    modutils = ModUtils(subreddit, options.site, options.verbose)
  File "/usr/local/lib/python3.5/site-packages/prawtools/mod.py", line 26, in __init__
    self.reddit = Reddit(site, disable_update_check=True, user_agent=AGENT)
  File "/usr/local/lib/python3.5/site-packages/praw/__init__.py", line 1069, in __init__
    super(AuthenticatedReddit, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/praw/__init__.py", line 535, in __init__
    super(OAuth2Reddit, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/praw/__init__.py", line 648, in __init__
    super(UnauthenticatedReddit, self).__init__(*args, **kwargs)
TypeError: __init__() got multiple values for argument 'user_agent'
```

**Comment by bboe** [comment]
I'll take a look this evening. It's possible that it was broken even before I updated to PRAW4.

**Comment by bboe** [comment]
Looks like you're right that the template options are not yet available in PRAW4. Now I have a reason to prioritize adding them.

**Comment by Aeon** [comment]
Made a couple of initial changes to get it off the ground.

**Comment by bboe** [comment]
Thanks for the contribution! I added the necessary template work to PRAW (https://github.com/praw-dev/praw/commit/74ae3715044c7c583015c1a86b0351aecac56ff1) and subsequently updated this package with the necessary changes for the `--sync` command. I didn't test anything else, so if there are other features that you would like to use and do not work, please file a new issue for them.
