### ISSUE TITLE
Donate spam

### ISSUE THREAD

**Issue by amici-ursi** [praw-dev/prawtools#42]
https://github.com/praw-dev/prawtools/blob/master/prawtools/stats.py#L31 on every post and in the subreddit sidebar surely violate reddit's self-promotion rule. If you want to include that in the code, you might want to disable it by default so others don't inadvertently advertise shady "give me cash" links.

**Comment by bboe** [comment]
@amici-ursi I understand your worried that such submissions may constitute spam. I took a quick look through the rules and faq (resources below) and didn't see anything specific to donations that the subreddit or its submissions are violating. Could you provide me a link to what you are referring to?

* https://www.reddit.com/wiki/faq
* https://www.reddit.com/wiki/selfpromotion

Thanks!

**Comment by bboe** [comment]
Closing. Please reopen if there are answers to my questions. If someone wants to make a PR to optionally disable the banner, I'd be open to that.
