### ISSUE TITLE
Everything says 0% right now

### ISSUE THREAD

**Issue by liamrosen** [praw-dev/prawtools#53]
![image](https://user-images.githubusercontent.com/718461/105569716-f828cb80-5cf8-11eb-8623-a673f6aaf19c.png)

**Comment by bboe** [comment]
I'm really not sure what I'm looking at.

**Comment by liamrosen** [comment]
https://subredditstats.com/

**Comment by bboe** [comment]
Fascinating. That website AFAIK has nothing to do with this project.
